chore: remove pushing while testing and add build job

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -5,7 +5,11 @@ on:
     - cron: "* */4 * * *" # every 4 hours
   push:
     branches:
-      - master
+      - develop
+      # - master
+  repository_dispatch:
+    # types: [develop, master]
+    types: [develop]
 
 jobs:
   job-sync-project-data:
@@ -18,23 +22,59 @@ jobs:
         uses: ./.github/actions/sync-data
         with:
           github-token: ${{ secrets.GITHUB_TOKEN }}
-          project-stats: "true"
+          project-stats: true
 
       - name: Commit data files
         run: |
           git config --local user.email "opensource+website@newrelic.com"
           git config --local user.name "Actionbot"
           echo "Updated project data files -- committing"
-          git commit src/data -m "chore: updated project data files"
+          git commit src/data -m "chore(stats): updated project stats files"
 
-      - name: Push Commit
-        uses: ad-m/github-push-action@v0.5.0
+      # - name: Push Commit
+      #   uses: ad-m/github-push-action@v0.5.0
+      #   with:
+      #     github_token: ${{ secrets.GITHUB_TOKEN }}
+
+  job-checkout-and-build:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout repo
+        uses: actions/checkout@v2
+
+      - name: Setup Node.js
+        uses: actions/setup-node@v1
         with:
-          github_token: ${{ secrets.GITHUB_TOKEN }}
+          node-version: 12
+
+      - name: Cache node_modules
+        id: cache-node
+        uses: actions/cache@v2
+        env:
+          cache-name: node-modules
+        with:
+          path: ~/.npm
+          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
+          restore-keys: |
+            ${{ runner.os }}-${{ env.cache-name }}-
+
+      - name: Install dependencies
+        run: npm ci
+
+      - name: Build
+        run: |
+          if [ '${{ github.ref }}' = 'refs/heads/develop' ]; then
+            npm run build:staging
+          elif [ '${{ github.ref }}' = 'refs/heads/master' ]; then
+            npm run build:production
+          else
+            echo "::error::Pull Request opened on unsupported branch. Exiting."
+            exit 1
+          fi
 
   job-deploy-staging:
     runs-on: ubuntu-latest
-    needs: job-sync-project-data
+    needs: [job-sync-project-data, job-checkout-and-build]
     env:
       STAGING_WEBHOOK: ${{ secrets.AMPLIFY_STAGING_WEBHOOK }}
     steps:
@@ -45,15 +85,15 @@ jobs:
           echo "**OUTPUT SUPPRESSED**"
           echo "Webhook call complete"
 
-  job-deploy-prod:
-    runs-on: ubuntu-latest
-    needs: job-sync-project-data
-    env:
-      PROD_WEBHOOK: ${{ secrets.AMPLIFY_PROD_WEBHOOK }}
-    steps:
-      - name: Call Amplify Prod Deploy
-        run: |
-          echo "Calling Amplify prod webhook"
-          curl --silent --show-error --output /dev/null -X POST $PROD_WEBHOOK -H "Content-Type:application/json"
-          echo "**OUTPUT SUPPRESSED**"
-          echo "Webhook call complete"
+  # job-deploy-prod:
+  #   runs-on: ubuntu-latest
+  #   needs: [job-sync-project-data, job-checkout-and-build]
+  #   env:
+  #     PROD_WEBHOOK: ${{ secrets.AMPLIFY_PROD_WEBHOOK }}
+  #   steps:
+  #     - name: Call Amplify Prod Deploy
+  #       run: |
+  #         echo "Calling Amplify prod webhook"
+  #         curl --silent --show-error --output /dev/null -X POST $PROD_WEBHOOK -H "Content-Type:application/json"
+  #         echo "**OUTPUT SUPPRESSED**"
+  #         echo "Webhook call complete"
