fix: generate release off develop branch and add third-party manifest/notices updates

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -3,7 +3,7 @@ name: CI
 on:
   push:
     branches:
-      - master
+      - develop
   repository_dispatch:
     types: [semantic-release]
 
@@ -35,13 +35,81 @@ jobs:
 
       - name: Gatsby Build
         run: npm run build:production
+  
+  job-generate-third-party-notices:
+    runs-on: ubuntu-latest
+    needs: job-checkout-and-build
+    steps:
+      # Checkout fetch-depth: 2 because there's a check to see if package.json
+      # was updated, and need at least 2 commits for the check to function properly
+      - name: Checkout repo
+        uses: actions/checkout@v2
+        with:
+          fetch-depth: 2
+
+      - name: Setup Node.js
+        uses: actions/setup-node@v1
+        with:
+          node-version: 10.x
+
+      - name: Download Cached Deps
+        id: cache-node-modules
+        uses: actions/cache@v1
+        env:
+          cache-name: node-modules
+        with:
+          path: ~/.npm
+          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
+          restore-keys: |
+            ${{ runner.os }}-${{ env.cache-name }}-
+
+      - name: Install Dependencies
+        run: npm ci
+
+      - name: Install OSS CLI
+        run: |
+          sudo npm install -g @newrelic/newrelic-oss-cli
+
+      - name: Generate Third Party Notices
+        id: generate-notices
+        run: |
+          if [ ! -f "third_party_manifest.json" ]; then
+            echo "::error::third_party_manifest.json is missing. Must generate using the newrelic-oss-cli."
+            exit 1
+          fi
+
+          # latest commit
+          LATEST_COMMIT=$(git rev-parse HEAD)
+
+          # latest commit where package.json was changed
+          LAST_CHANGED_COMMIT=$(git log -1 --format=format:%H --full-diff package.json)
+
+          if [ $LAST_CHANGED_COMMIT = $LATEST_COMMIT ]; then
+            git config user.email "${{ env.THIRD_PARTY_GIT_AUTHOR_EMAIL }}"
+            git config user.name "${{ env.THIRD_PARTY_GIT_AUTHOR_NAME }}"
+
+            oss third-party manifest
+            oss third-party notices
+
+            git add third_party_manifest.json
+            git add THIRD_PARTY_NOTICES.md
+
+            git commit -m 'chore: update third-party manifest and notices [skip-cd]'
+            echo "::set-output name=commit::true"
+          else
+            echo "No change in package.json, not regenerating third-party notices"
+          fi
 
   job-generate-release:
     runs-on: ubuntu-latest
     needs: job-checkout-and-build
     steps:
+      # Checkout ref: develop because previous job potentially committed third_party_notices and
+      # we need to checkout latest to pick up that commit
       - name: Checkout repo
         uses: actions/checkout@v2
+        with:
+          ref: master
 
       - name: Setup Node.js
         uses: actions/setup-node@v1
@@ -61,8 +129,8 @@ jobs:
 
       - name: Install dependencies
         run: npm ci
-      # Don't actually run release yet
-      # - name: Release
-      #   env:
-      #     GITHUB_TOKEN: ${{ secrets.OPENSOURCE_BOT_TOKEN }}
-      #   run: npx semantic-release
+      
+      - name: Release
+        env:
+          GITHUB_TOKEN: ${{ secrets.OPENSOURCE_BOT_TOKEN }}
+        run: npx semantic-release
